from tkinter import *
window=Tk()
window.title("login app")
window.geometry("400x400")
frame=Frame(master=window,height=200,width=360,bg="blue")
lbl1=Label(frame,text="enter your name",bg="blue",fg='white')
lbl2=Label(frame,text="enter your username",bg="blue",fg='white')
lbl3=Label(frame,text="enter your email id",bg="blue",fg='white')
name_entry=Entry(frame)
email_entry=Entry(frame)
pass_entry=Entry(frame,show="*")
def display():
    name=name_entry.get()
    greet="hey"+name
    message="\ncongratulations for your new account!"
    textbox.insert(END,greet)
    textbox.insert(END,message)
textbox=Text(bg="white",fg="blue")
btn=Button(text="create account",command=display,bg="red")
frame.place(x=20,y=0)
lbl1.place(x=20,y=20)
name_entry.place(x=150,y=20)
lbl2.place(x=20,y=80)
email_entry.place(x=150,y=80)
lbl3.place(x=20,y=140)
pass_entry.place(x=150,y=140)
btn.place(x=130,y=210)
textbox.place(y=250)
window.mainloop()